package eu.su.mas.dedaleEtu.mas.agents.dummies.sid.bdi.Lab3.bdi.agent;

public enum BdiStates {
    INITIAL,
    UPDATE_REQUEST_SENT,
    UPDATE_REQUEST_AGREED,
    UPDATED,
    MOVEMENT_COMPUTED,
    MOVEMENT_REQUEST_SENT,
    MOVEMENT_REQUEST_AGREED,
    MOVEMENT_END,
    SHOUT_ONTOLOGY_REQUEST_SENT,
    SHOUT_ONTOLOGY_REQUEST_AGREED,
}
